palette = "oxocarbon"

[palettes.oxocarbon]
rosewater = "#f2f4f8"
mauve = "#be95ff"
blue = "#33b1ff"
green = "#42be65"
yellow = "#ee5396"
red = "#ee5396"
text = "#f2f4f8"
surface0 = "#393939"

format = """
[](fg:surface0)$os$username[](bg:surface0 fg:blue)$directory[](fg:blue bg:surface0)$git_branch$git_status[](fg:surface0)
$character"""

[directory]
style = "bg:surface0 fg:text"
format = "[ $path ]($style)"

[git_branch]
style = "bg:surface0 fg:mauve"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:surface0 fg:red"
format = "[$all_status$ahead_behind ]($style)"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
