font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        11.0

background            #161616
foreground            #f2f4f8
cursor                 #f2f4f8
selection_background   #41414D

color0  #161616
color1  #3ddbd9
color2  #33b1ff
color3  #ee5396
color4  #42be65
color5  #be95ff
color6  #ff7eb6
color7  #f2f4f8
color8  #525252
color9  #78a9ff
color10 #ff7eb6
color11 #be95ff
color12 #dde1e6
color13 #ffffff
color14 #82cfff
color15 #08bdba

background_opacity   0.95
window_padding_width 8
confirm_os_window_close 0
